# configs/default_config.yaml
model:
  name: "microsoft/unixcoder-base"
  num_prompts: 4
  prompt_length: 8
  embed_dim: 768
  num_classes: 2
  max_length: 512
  chunk_size: 512
  stride: 256

training:
  batch_size: 8
  learning_rate: 0.00002
  epochs: 10
  warmup_steps: 100
  weight_decay: 0.01
  gradient_accumulation: 4

evaluation:
  batch_size: 8
  metrics: ["accuracy", "f1", "precision", "recall", "roc_auc"]
  space_metrics: true
  ksp_simulation: true

paths:
  model_dir: "models/"
  data_dir: "data/"
  output_dir: "outputs/"
  

device: "auto"  # auto, cpu, cuda, mps
